### ISSUE TITLE
Getting error running ./craft migrate/all

### ISSUE THREAD

**Issue by keithmancuso** [craftcms/contact-form#129]
```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getValidatedBodyParam()'

in /home/forge/ryanhealth.org/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /home/forge/ryanhealth.org/config/contact-form.php(4): yii\base\Component->__call('getValidatedBod...', Array)
#1 /home/forge/ryanhealth.org/vendor/craftcms/cms/src/services/Config.php(174): include('/home/forge/rya...')
#2 /home/forge/ryanhealth.org/vendor/craftcms/cms/src/services/Plugins.php(767): craft\services\Config->getConfigFromFile('contact-form')
#3 /home/forge/ryanhealth.org/vendor/craftcms/cms/src/services/Plugins.php(199): craft\services\Plugins->createPlugin('contact-form', Array)
#4 /home/forge/ryanhealth.org/vendor/craftcms/cms/src/base/ApplicationTrait.php(1124): craft\services\Plugins->loadPlugins()
#5 /home/forge/ryanhealth.org/vendor/craftcms/cms/src/console/Application.php(59): craft\console\Application->_init()
#6 /home/forge/ryanhealth.org/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#7 /home/forge/ryanhealth.org/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#8 /home/forge/ryanhealth.org/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#9 /home/forge/ryanhealth.org/vendor/craftcms/cms/src/console/Application.php(48): yii\console\Application->__construct(Array)
#10 [internal function]: craft\console\Application->__construct(Array)
#11 /home/forge/ryanhealth.org/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#12 /home/forge/ryanhealth.org/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
#13 /home/forge/ryanhealth.org/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
#14 /home/forge/ryanhealth.org/vendor/craftcms/cms/bootstrap/bootstrap.php(249): yii\BaseYii::createObject(Array)
#15 /home/forge/ryanhealth.org/vendor/craftcms/cms/bootstrap/console.php(31): require('/home/forge/rya...')
#16 /home/forge/ryanhealth.org/craft(21): require('/home/forge/rya...')
#17 {main}
```

**Comment by keithmancuso** [comment]
Thanks for the fix Brandon, works now
